### ISSUE TITLE
unknown keyword: :engine (ArgumentError)

### ISSUE THREAD

**Issue by mathyouf** [12joan/please#3] opened 2023-01-06 07:30 UTC
**Error**
```
please echo hi

/home/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ruby-openai-3.0.2/lib/ruby/openai/client.rb:10:in `completions': unknown keyword: :engine (ArgumentError)
        from /home/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/openai-please-0.1.3/lib/please/openai/codex_service.rb:11:in `completion'
        from /home/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/openai-please-0.1.3/lib/please/request.rb:6:in `send'
        from /home/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/openai-please-0.1.3/lib/please/cli.rb:91:in `<top (required)>'
        from <internal:/home/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/home/user/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/user/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/openai-please-0.1.3/exe/please:4:in `<top (required)>'
        from /home/user/.rbenv/versions/3.2.0/bin/please:25:in `load'
        from /home/user/.rbenv/versions/3.2.0/bin/please:25:in `<main>'
```

**Env Details**
```
which please
/home/user/.rbenv/shims/please
ruby --version    
ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-linux]
```

**Notes**
- I tried switching to Ruby 3.0.5 as well
- I'm using `export OPENAI_ACCESS_TOKEN=string`
- I tried formats `export OPENAI_ACCESS_TOKEN=[string]` and `export OPENAI_ACCESS_TOKEN="string"` and the error persisted

**Comment by MrJarnould** [comment] 2023-01-07 00:53
+1 I have the same bug.

**Comment by 12joan** [comment] 2023-01-13 23:02
Thanks for letting me know! It should be fixed now.

Closing as a duplicate of #2.

**Closed by 12joan** 2023-01-13 23:02 UTC
